#!/usr/bin/env bash
# 
# This is a script written to test TrafficTracker
# (http://github.com/iuuso/TrafficTracker)
#
# Source: http://mostpopularwebsites.net/
# Date fetched: 3.7.2013 10:44
# Contact: iuuso @ IRC (freenode, ircnet)
# 
# Erased from the original list: 
# 	www.googleusercontent.com (42) due to 404 -> replaced with akamaihd.net (53)
# Numbers 51 (google.it) and 52 (google.ru) were skipped due to boringess

sites=("http://www.facebook.com" 
	"http://www.google.com"
	"http://www.youtube.com"
	"http://www.yahoo.com"
	"http://www.amazon.com"
	"http://www.baidu.com"
	"http://www.wikipedia.org"
	"http://www.live.com"
	"http://www.qq.com"
	"http://www.taobao.com"
	"http://www.google.co.in"
	"http://www.twitter.com"
	"http://www.blogspot.com"
	"http://www.yahoo.co.jp"
	"http://www.linkedin.com"
	"http://www.bing.com"
	"http://www.sina.com.cn"
	"http://www.yandex.ru"
	"http://www.vk.com"
	"http://www.ask.com"
	"http://www.163.com"
	"http://www.ebay.com"
	"http://www.google.com.hk"
	"http://www.tumblr.com"
	"http://www.delta-search.com"
	"http://www.msn.com"
	"http://www.google.de"
	"http://www.hao123.com"
	"http://www.weibo.com"
	"http://www.wordpress.com"
	"http://www.amazon.co.jp"
	"http://www.xvideos.com"
	"http://www.google.co.jp"
	"http://www.mail.ru"
	"http://www.google.co.uk"
	"http://www.google.com.br"
	"http://www.fc2.com"
	"http://www.microsoft.com"
	"http://www.tmall.com"
	"http://www.odnoklassniki.ru"
	"http://www.conduit.com"
	"http://www.google.fr"
	"http://www.akamaihd.net"
	"http://www.babylon.com"
	"http://www.xhamster.com"
	"http://www.craigslist.org"
	"http://www.instagram.com"
	"http://www.pinterest.com"
	"http://www.sohu.com"
	"http://www.amazon.de");


#browser="/usr/lib/chromium/chromium --incognito --app="
browser="/usr/bin/firefox -private "
i=0

while true	
	do
		if [ "$i" -lt 50 ] 
			then
			pkill -9 firefox 
			echo "Launching $browser with site number $i : ${sites[i]}"
			$browser${sites[i]} > log & sleep 20
			grep ERROR log && break
			pkill -9 firefox
			echo "Browser killed...."
			i=$(($i+1))
		else 
			echo "Limit reached." 
			exit
		fi
done

