#!/usr/bin/env bash
# 
# This is a script written to test TrafficTracker
# (http://github.com/iuuso/TrafficTracker)
#
# Source: http://mostpopularwebsites.net/
# Date fetched: 3.7.2013 10:44
# Contact: iuuso @ IRC (freenode, ircnet)
# 
# Erased from the original list: 
# 	www.googleusercontent.com (42) due to 404 -> replaced with akamaihd.net (53)
# Numbers 51 (google.it) and 52 (google.ru) were skipped due to boringess

sites=("www.facebook.com" 
	"www.google.com"
	"www.youtube.com"
	"www.yahoo.com"
	"www.amazon.com"
	"www.baidu.com"
	"www.wikipedia.org"
	"www.live.com"
	"www.qq.com"
	"www.taobao.com"
	"www.google.co.in"
	"www.twitter.com"
	"www.blogspot.com"
	"www.yahoo.co.jp"
	"www.linkedin.com"
	"www.bing.com"
	"www.sina.com.cn"
	"www.yandex.ru"
	"www.vk.com"
	"www.ask.com"
	"www.163.com"
	"www.ebay.com"
	"www.google.com.hk"
	"www.tumblr.com"
	"www.delta-search.com"
	"www.msn.com"
	"www.google.de"
	"www.hao123.com"
	"www.weibo.com"
	"www.wordpress.com"
	"www.amazon.co.jp"
	"www.xvideos.com"
	"www.google.co.jp"
	"www.mail.ru"
	"www.google.co.uk"
	"www.google.com.br"
	"www.fc2.com"
	"www.microsoft.com"
	"www.tmall.com"
	"www.odnoklassniki.ru"
	"www.conduit.com"
	"www.google.fr"
	"www.akamaihd.net"
	"www.babylon.com"
	"www.xhamster.com"
	"www.craigslist.org"
	"www.instagram.com"
	"www.pinterest.com"
	"www.sohu.com"
	"www.amazon.de");


#browser="/usr/lib/chromium/chromium"
browser="/usr/bin/firefox -new-instance"
i=0

while true	
	do
		if [ "$i" -lt 50 ] 
			then
			pkill -9 firefox
			echo "Launching $browser with site number $i : ${sites[i]}"
			$browser ${sites[i]} > log & sleep 10
			grep ERROR log && break
			pkill -9 iceweasel
			echo "Browser killed...."
			i=$(($i+1))
		else 
			echo "Limit reached." 
		fi
done

